### DISCUSSION TITLE
一些问题的建议优化

### DISCUSSION THREAD

**Discussion by kokorousaki** [Samarium150/mirai-console-lolicon#54] [Q&A] [answered]
1.关于冷却时间，我试了一下，在Q群里，发现所有人是共用冷却时间的，例如A发了涩图 get命令，B要等冷却介绍后再发命令才能获取到图片，这个是不是应该按群员独立计算的
2.怎么屏蔽个别群，例如我只想让群A可以发送命令，而群B发送没反应
3.关于代理，我配置了SOCK5后貌似不支持（sslocal的），HTTP的可以，不知道是不是格式的问题，只填主机和sock5端口就可以了吗

**Comment by Samarium150** [comment]
1. 群里的冷却时间如果按群员来计算的话，依然会有刷屏的可能。
2. 已在 #47 回复
3. 理论来说写成 
```yaml
# 可选：DIRECT/HTTP/SOCKS
type: SOCKS
# 地址
hostname: localhost
# 端口
port: 1080
```
应该就可以了

**Comment by Samarium150** [comment]
测试的时候发现了个新问题，写在了 #53 ，简单来说就是bot master在白名单模式下不会被加入`userSet`

**Comment by kokorousaki** [comment]
> 测试的时候发现了个新问题，写在了 #53 ，简单来说就是bot master在白名单模式下不会被加入`userSet`

试了一下，白名单把机器人加入白名单，依旧会无视whitelist

**Comment by Samarium150** [comment]
> > 测试的时候发现了个新问题，写在了 #53 ，简单来说就是bot master在白名单模式下不会被加入`userSet`
> 
> 试了一下，白名单把机器人加入白名单，依旧会无视whitelist

你是说把bot自己放在白名单里吗

**Comment by kokorousaki** [comment]
> > > 测试的时候发现了个新问题，写在了 #53 ，简单来说就是bot master在白名单模式下不会被加入`userSet`
> > 
> > 
> > 试了一下，白名单把机器人加入白名单，依旧会无视whitelist
> 
> 你是说把bot自己放在白名单里吗

是的

**Reply by Samarium150** [reply]
没有把bot自己放在白名单里的必要性吧

**Comment by kokorousaki** [comment]
![image](https://user-images.githubusercontent.com/87707351/133050659-e95fd88d-1a89-4135-81c6-ffe565c07346.png)
贴一张sock报错的图

**Reply by Samarium150** [reply]
没复现出来，我的SOCKS代理工作正常

```yaml
# 可选：DIRECT/HTTP/SOCKS
type: SOCKS
# 地址
hostname: localhost
# 端口
port: 1089
```

```
2021/09/13 17:12:28 tcp:127.0.0.1:14576 accepted tcp:api.lolicon.app:443
2021/09/13 17:12:29 tcp:127.0.0.1:14578 accepted tcp:i.pixiv.cat:443
```

你的java是11吗
