### ISSUE TITLE
一些问题的建议优化

### ISSUE THREAD

**Issue by kokorousaki** [Samarium150/mirai-console-lolicon#52]
1.关于冷却时间，我试了一下，在Q群里，发现所有人是共用冷却时间的，例如A发了涩图 get命令，B要等冷却介绍后再发命令才能获取到图片，这个是不是应该按群员独立计算的
2.怎么屏蔽个别群，例如我只想让群A可以发送命令，而群B发送没反应
3.关于代理，我配置了SOCK5后貌似不支持（sslocal的），HTTP的可以，不知道是不是格式的问题，只填主机和sock5端口就可以了吗

**Comment by Samarium150** [comment]
1. 群里的冷却时间如果按群员来计算的话，依然会有刷屏的可能。
2. 已在 #47 回复
3. 理论来说写成 
```yaml
# 可选：DIRECT/HTTP/SOCKS
type: SOCKS
# 地址
hostname: localhost
# 端口
port: 1080
```
应该就可以了
